### ISSUE TITLE
Diminuer le volume de log de l'API

### ISSUE THREAD

**Issue by alavenant** [ign-gpao/api#33]

**Comment by IGNBPesty** [comment]
+1 

Les logs de l'API ont tendance à générer beaucoup de volume ce qui peut entraîner des problèmes de consommation d'espace disque.

Dans le cadre de LidarHD la GPAO est installée en service, on a reconfiguré pour ne pas sortir les logs stdout histoire de contourner le problème.


[Service]
WorkingDirectory=/var/data/gpao/api
ExecStart=npm start
Restart=always
RestartSec=10
StandardOutput=null
StandardError=journal
